/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestAuthenticate } from "./TestAuthenticate";
export type { TestConfig } from "./TestConfig";
export type { TestProxy } from "./TestProxy";
export type { TestShares } from "./TestShares";
export type { TestToken } from "./TestToken";
