/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAuthenticate } from "./IAuthenticate";
export type { IConfig } from "./IConfig";
export type { ILauncher } from "./ILauncher";
export type { IMakeFriendCoin } from "./IMakeFriendCoin";
export type { IPowerPoint } from "./IPowerPoint";
export type { IPowerStore } from "./IPowerStore";
export type { IShares } from "./IShares";
