/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as test from "./test";
export { Launcher__factory } from "./Launcher__factory";
export { MakeFriendsCoin__factory } from "./MakeFriendsCoin__factory";
