/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestAuthenticate__factory } from "./TestAuthenticate__factory";
export { TestConfig__factory } from "./TestConfig__factory";
export { TestProxy__factory } from "./TestProxy__factory";
export { TestShares__factory } from "./TestShares__factory";
export { TestToken__factory } from "./TestToken__factory";
