/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAuthenticate,
  IAuthenticateInterface,
} from "../../../contracts/interfaces/IAuthenticate";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "shareId",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "twitterId",
        type: "uint256",
      },
    ],
    name: "authorizeTwitter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "twitterId",
        type: "uint256",
      },
    ],
    name: "getShareIdByTwitterId",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "shareId",
        type: "address",
      },
    ],
    name: "getShareTwitterId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "shareId",
        type: "address",
      },
    ],
    name: "isAuthorized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAuthenticate__factory {
  static readonly abi = _abi;
  static createInterface(): IAuthenticateInterface {
    return new utils.Interface(_abi) as IAuthenticateInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAuthenticate {
    return new Contract(address, _abi, signerOrProvider) as IAuthenticate;
  }
}
