/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFeeWithdraw,
  IFeeWithdrawInterface,
} from "../../../contracts/interfaces/IFeeWithdraw";

const _abi = [
  {
    inputs: [],
    name: "withdrawProtocolFees",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "shareId",
        type: "address",
      },
    ],
    name: "withdrawShareFees",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFeeWithdraw__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeWithdrawInterface {
    return new utils.Interface(_abi) as IFeeWithdrawInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFeeWithdraw {
    return new Contract(address, _abi, signerOrProvider) as IFeeWithdraw;
  }
}
