/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAuthenticate__factory } from "./IAuthenticate__factory";
export { IConfig__factory } from "./IConfig__factory";
export { ILauncher__factory } from "./ILauncher__factory";
export { IMakeFriendCoin__factory } from "./IMakeFriendCoin__factory";
export { IPowerPoint__factory } from "./IPowerPoint__factory";
export { IPowerStore__factory } from "./IPowerStore__factory";
export { IShares__factory } from "./IShares__factory";
