/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPowerStore,
  IPowerStoreInterface,
} from "../../../contracts/interfaces/IPowerStore";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "shareId",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "injectPower",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPowerStore__factory {
  static readonly abi = _abi;
  static createInterface(): IPowerStoreInterface {
    return new utils.Interface(_abi) as IPowerStoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPowerStore {
    return new Contract(address, _abi, signerOrProvider) as IPowerStore;
  }
}
